
##CARPETA - ARCHIVO CONTROL TP PACKING
DRIVE_ID_TRANSPORTE_PACKING = "b!f3MMUg71uUqelwZOTUNO5oiKerqyJU9Ak-AZ9LzQ99ZkHDdWCq1PSIkHUkGprAyU"
ITEM_ID_TRANSPORTE_PACKING = "01R5XM75GZQSWFSCRU2JALC3SWHIE6ETT7"

#NAME INPUT
FILE_NAME_TRANSPORTE_PACKING = "CONTROL TP PACKING.xlsx"
FILE_NAME_PROCESADO_TPPACKING = "PROCESADO TP PACKING.xlsx"



#NAME OUTPUT
FILE_NAME_PROCESADO_CONCESIONARIO_PACKING = "PROCESADO CONCESIONARIO PACKING.xlsx"

FILE_NAME_PROCESADO_TIEMPOS_PACKING = "TIEMPOS PACKING.xlsx"


###SAVE GENERAL MY STORAGE
DRIVE_ID_CARPETA_STORAGE = "b!M5ucw3aa_UqBAcqv3a6affR7vTZM2a5ApFygaKCcATxyLdOhkHDiRKl9EvzaYbuR"

#CARPETA ALZA PIPELINE
FOLDER_ID_CARPETA_STORAGE = "01XOBWFSBLVGULAQNEKNG2WR7CPRACEN7Q"
#CARPETA TIEMPOS PACKING
FOLDER_ID_CARPETA_STORAGE_TIEMPOS = "01XOBWFSFLMQ3FGVMGKFHLDT6X3B7U3GTZ"
